### ISSUE TITLE
Using 3D convolution

### ISSUE THREAD

**Issue by chinmay5** [keyu-tian/SparK#55]
Thank you so much for sharing the code base. I was wondering how to apply 3d convolution using the setup. I think we need to update the section

```
def sp_conv_forward(self, x: torch.Tensor):
    x = super(type(self), self).forward(x)
    x *= _get_active_ex_or_ii(H=x.shape[2], W=x.shape[3], returning_active_ex=True)    # (BCHW) *= (B1HW), mask the output of conv
    return x
```

However, I am not certain. It would be great to know your opinion. Any suggestions about things to keep in mind during the implementation of 3D conv would be highly appreciated.

**Comment by keyu-tian** [comment]
@chinmay5 if you're using 3d conv for video, you may mimic writing `_cur_active`, `_get_active_ex_or_ii`, etc., as 3D version. `_cur_active` would be a BCHWT-like binary tensor.

If it is for 3d point cloud or 3d sparse voxel processing, i would recommend you to use the sparse conv of https://github.com/NVIDIA/MinkowskiEngine rather than ours for efficiency.

**Comment by chinmay5** [comment]
Thank you so much for your input
